project:
  type: website
  output-dir: docs

website:
  title: "![](/Figures/MeasurementMachineLearningLab.png){width=150px}"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: Team
      - text: Projects
        menu:
          - text: "Model Fit"
            href: modelfit.qmd
          - text: "Measurement Invariance"
            href: mi.qmd
          - text: "Dimensionality Assessment"
            href: dim.qmd
      - news.qmd
  page-footer:
    #center:
    center: "[Measurement and Machine Learning Lab](index.qmd)"
    right: "![](/Figures/MMLLab.png){width=70px}"
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual

