project:
  type: website
  output-dir: docs

website:
  title: "Measurement & Machine Learning Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: Team
      - href: projects.qmd
        text: Projects
      - news.qmd
  page-footer:
    center:
      - text: Measurement and Machine Learning Lab
        href: index.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual

