---
title: "Dimensionality Assessment in Exploratory Factor Analysis"
---

In this project, we combine extensive data simulations and supervised machine learning to create new factor retention criteria that can accurately predict the dimensionality of a latent concept given various data characteristics. In simulation studies, these machine-learning-based approaches show a consistently higher accuracy than common factor retention criteria as well as higher replicability rates for empirical data sets.

**Selected Publications and Preprints:**

Goretzko, D., & Bühner, M. (2020). One model to rule them all? Using machine learning algorithms to determine the number of factors in exploratory factor analysis. Psychological Methods, 25(6), 776–786. <https://doi.org/10.1037/met0000262>

Goretzko, D., & Bühner, M. (2022). Factor retention using machine learning with ordinal data. Applied Psychological Measurement, 46(5), 406-421. <https://doi.org/10.1177/01466216221089345>

Goretzko, D., & Ruscio, J. (2024). The Comparison Data Forest – A new comparison data approach to determine the number of factors in exploratory factor analysis. Behavior Research Methods. [https://doi.org/10.3758/s13428-023-02122-4](https://doi.org/10.3758/s13428-023-02122-4%5D)

Goretzko, D. (2025). How many factors to retain in exploratory factor analysis? A critical overview of factor retention methods. Psychological Methods. <https://doi.org/10.1037/met0000733>

Goretzko, D., Partsch, M. V., & Sterner, P. (2025). Embrace the heterogeneity in EFA but be transparent about what you do – A commentary on Manapat et al. (2023). Psychological Methods. <https://doi.org/10.1037/met0000759>
