---
title: "Measurement & Machine Learning Lab"
---

Welcome to the **Measurement and Machine Learning Lab** (MMLL). Our goal is to improve psychological measurement by combining psychometric approaches and latent variable modeling with modern machine learning and data science tools. Our research addresses different issues related to the measurement of latent variables such as dimensionality assessment, measurement invariance, model fit evaluation, model specification, fairness, and replicability or generalizability.

Our lab unites psychologists, statisticians, and methodologists who share an interest in measurement topics, latent variable modeling, and psychometrics as well as computational statistics, machine learning, and data science.

The  lab is led by [Prof. Dr. David Goretzko](https://dgoretzko.github.io/Measurement-ML/people.html#prof.-dr.-david-goretzko) from Goethe University Frankfurt. The MMLL brings together members from his work group in Frankfurt, researchers from other German universities (e.g., [Dr. Philipp Sterner](https://dgoretzko.github.io/Measurement-ML/people.html#dr.-philipp-sterner) from TU Munich), and international partners (e.g., [Dr. Melanie Partsch](https://dgoretzko.github.io/Measurement-ML/people.html#dr.-melanie-viola-partsch) from Utrecht University).

f you are interested in collaborating, pursuing a research internship in our lab, or exchanging research ideas more broadly, please feel free to [contact](mailto:goretzko@psych.uni-frankfurt.de){.email} us.

<!-- **Contact:** -->
