---
title: "News and Upcoming Events"
---

## Workshops & Talks

**Workshop on Measurement Invariance Testing**

On September 28 2025, David and Philipp offer a pre-conference workshop at the FGME 2025 in Berlin with the title *New Perspectives on Measurement Invariance Testing*. The workshop will cover both newly developed methods for measurement invariance exploration and a causal framework of invariance analyses. More information can be found on the [conference website](http://methods-berlin.com/en/fgme2025_workshops/).

\

**Workshop on New Methods for Model Fit Evaluation in SEM**

On September 21 2025, Melanie and David offer a pre-conference workshop at the DPPD 2025 in Kassel with the title *Established and innovative methods to evaluate model fit in structural equation modeling*. This workshop introduces new strategies to evaluate model fit in SEM including dynamic fit cutoffs (McNeish & Wolf, 2023) and machine learning based approaches (Partsch & Goretzko, 2024/under review). More information can be found on the [conference website](https://dppd2025.de/programm/pre-conference-workshops/).

\

**European Congress of Methodology 2025**

On Tuesday, 22nd of July 2025, we (Melanie, Philipp, and David) organize a pre-conference workshop on *New Perspectives on Measurement Invariance Testing* at the EAM 2025 at the University of La Laguna in San Cristobal de La Laguna, Tenerife. More information can be found on the [conference website](https://eam2025.eu). We will also present our research in a symposium called "Measurement and Machine Learning" that will be chaired by Melanie.

\

**Keynote and Workshop at the ICCPAE 2025**

David has been invited to give a keynote speech and a workshop on machine learning in psychological assessment at the 
*International Conference on Cognitive and Psychological Assessment and Enhancement (ICCPAE 2025)* in Beijing (11/07/2025 - 13/07/2025).

\

**Workshop on Machine Learning Methods for Modeling in Psychology**

As part of the *Statistical Modeling in Psychology* (SMiP) Summer School 2025 (30/06/2025 - 04/07/2025), David and Philipp will provide a workshop on machine learning modeling with a focus on its applicability to psychological research and assessment. Besides covering general aspects of machine learning, approaches for interpretable machine learning and cost-sensitive learning are discussed in the workshop. More information can be found on the [SMiP hompage](https://www.uni-mannheim.de/smip-summerschool/workshops/machine-learning-methods-for-modeling-in-psychology/).

\

**Introduction to Machine Learning at the University Trento (Department of Psychology and Cognitive Science)**

On Tuesday, May 27 2025, David will give an *Introduction to Supervised Machine Learning in Psychology* at the University of Trento. The talk (+ workshop-style exercise) will focus on key concepts of machine learning modeling - such as resampling strategies, hyperparameter tuning, and performance evaluation. More information can be found on the [website](https://beyond.dipsco.unitn.it/home-page) of the University of Trento .

## New Publications

We are delighted that our paper *Detecting model misfit in structural equation modeling with machine learning—A proof of concept* was accepted for publication in *Multivariate Behavioral Research* and will be published online soon:

Partsch, M. V., & Goretzko, D. (2025). Detecting model misfit in structural equation modeling with machine learning—A proof of concept. *Multivariate Behavioral Research*. Advance online publication. <https://doi.org/10.1080/00273171.2025.2552304>

\

Our paper *Quantifying Measurement Non-Invariance Beyond Simple Structure: The Closed Formulas of Universal Effect Size Measures for MI.* was accepted for publication in *Structural Equation Modeling: A Multidisciplinary Journal* and will be published online soon:

Schuhbeck, T. M. B., Sterner, P., & Goretzko, D. (2025). Quantifying Measurement Non-Invariance Beyond Simple Structure: The Closed Formulas of Universal Effect Size Measures for MI. Structural Equation Modeling: A Multidisciplinary Journal. <https://doi.org/10.1080/10705511.2025.2570447>

\

Our paper introducing *Exploratory Graph Analysis Trees (EGA Trees)* has been accepted for publication in *Psychological Methods*:

Goretzko, D., & Sterner, P. (accepted for publication). Exploratory Graph Analysis Trees – A Network-based Approach to Investigate Measurement Invariance with Numerous Covariates. *Psychological Methods*. Preprint: <https://doi.org/10.31234/osf.io/9cx8z>.

\

Recently, our paper *A Simulation Study on the Interaction Effects of Underfactoring and Nuisance Parameters on Model Fit Indices.* was accepted for publication in *Structural Equation Modeling: A Multidisciplinary Journal*:

Partsch, M. V., Sterner, P., & Goretzko, D. (2025). A Simulation Study on the Interaction Effects of Underfactoring and Nuisance Parameters on Model Fit Indices. *Structural Equation Modeling: A Multidisciplinary Journal*. <https://doi.org/10.1080/10705511.2025.2514592>.

\

Our tutorial paper *Assessing Measurement Invariance with Exploratory Factor Analysis Trees: A Practical Guide.* has been accepted for publication in the *European Journal of Psychological Assessment*:

Straub, N., Goretzko, D., & Sterner, P. (2025) Assessing Measurement Invariance with Exploratory Factor Analysis Trees: A Practical Guide. European Journal of Psychological Assessment. <https://doi.org/10.1027/1015-5759/a000898>

\

We are delighted to share that our paper *Embrace the heterogeneity in EFA but be transparent about what you do – A commentary on Manapat et al. (2023)* has been accepted for publication in *Psychological Methods*:

Goretzko, D., Partsch, M. V., & Sterner, P. (2025). Embrace the heterogeneity in EFA but be transparent about what you do – A commentary on Manapat et al. (2023). Psychological Methods. <https://doi.org/10.1037/met0000759>
